const jobs = [
  { name: 'Entregador', emoji: '🛵', pay: [35, 60], description: 'Faça entregas rápidas pela cidade.' },
  { name: 'Pescador', emoji: '🎣', pay: [45, 75], description: 'Pesque e venda sua pescaria.' },
  { name: 'Garçom', emoji: '🍽️', pay: [40, 70], description: 'Atenda clientes e sirva pedidos.' },
  { name: 'Cozinheiro', emoji: '🍳', pay: [50, 85], description: 'Prepare pratos e refeições.' },
  { name: 'Agricultor', emoji: '🌾', pay: [45, 80], description: 'Cuide da plantação e colha recursos.' },
  { name: 'Jardineiro', emoji: '🌱', pay: [40, 75], description: 'Cuide de jardins e áreas verdes.' },
  { name: 'Motorista', emoji: '🚗', pay: [55, 90], description: 'Transporte pessoas pela cidade.' },
  { name: 'Mecânico', emoji: '🔧', pay: [60, 100], description: 'Conserte veículos e máquinas.' },
  { name: 'Eletricista', emoji: '⚡', pay: [65, 105], description: 'Resolva problemas elétricos.' },
  { name: 'Encanador', emoji: '🔩', pay: [60, 100], description: 'Conserte tubulações e instalações.' },
  { name: 'Pedreiro', emoji: '🧱', pay: [55, 95], description: 'Construa e reforme estruturas.' },
  { name: 'Arquiteto', emoji: '📐', pay: [75, 120], description: 'Planeje construções e projetos.' },
  { name: 'Engenheiro', emoji: '👷', pay: [85, 135], description: 'Resolva projetos e desafios técnicos.' },
  { name: 'Programador', emoji: '💻', pay: [60, 95], description: 'Resolva tarefas e desenvolva sistemas.' },
  { name: 'Desenvolvedor', emoji: '🧑‍💻', pay: [75, 125], description: 'Crie aplicações e soluções digitais.' },
  { name: 'Designer', emoji: '🎨', pay: [65, 110], description: 'Crie artes, interfaces e identidades visuais.' },
  { name: 'Fotógrafo', emoji: '📸', pay: [55, 100], description: 'Registre momentos e produza ensaios.' },
  { name: 'Jornalista', emoji: '📰', pay: [65, 105], description: 'Investigue acontecimentos e produza notícias.' },
  { name: 'Professor', emoji: '🧑‍🏫', pay: [70, 115], description: 'Ensine e ajude outras pessoas a aprender.' },
  { name: 'Cientista', emoji: '🧪', pay: [80, 130], description: 'Pesquise e faça descobertas.' },
  { name: 'Médico', emoji: '🩺', pay: [90, 135], description: 'Atenda pacientes e cuide da saúde.' },
  { name: 'Veterinário', emoji: '🐾', pay: [75, 120], description: 'Cuide da saúde dos animais.' },
  { name: 'Bombeiro', emoji: '🚒', pay: [80, 130], description: 'Atue em missões de emergência.' },
  { name: 'Policial', emoji: '👮', pay: [75, 125], description: 'Proteja a cidade e cumpra missões.' },
  { name: 'Detetive', emoji: '🕵️', pay: [85, 140], description: 'Resolva casos e encontre pistas.' },
  { name: 'Astronauta', emoji: '🚀', pay: [110, 180], description: 'Explore o espaço e participe de missões.' },
  { name: 'Piloto', emoji: '✈️', pay: [95, 155], description: 'Pilote aeronaves e transporte passageiros.' },
  { name: 'Marinheiro', emoji: '⚓', pay: [65, 110], description: 'Trabalhe em viagens e missões marítimas.' },
  { name: 'Mergulhador', emoji: '🤿', pay: [70, 120], description: 'Explore o fundo do mar em missões especiais.' },
  { name: 'Guia Turístico', emoji: '🗺️', pay: [50, 90], description: 'Mostre lugares e conte histórias aos visitantes.' },
  { name: 'Streamer', emoji: '🎮', pay: [70, 130], description: 'Faça transmissões e entretenha seu público.' },
  { name: 'Criador de Conteúdo', emoji: '📱', pay: [65, 120], description: 'Produza conteúdo para a internet.' },
  { name: 'Cantor', emoji: '🎤', pay: [70, 125], description: 'Faça apresentações e shows.' },
  { name: 'Músico', emoji: '🎸', pay: [65, 115], description: 'Toque instrumentos e participe de apresentações.' },
  { name: 'Ator', emoji: '🎭', pay: [70, 125], description: 'Participe de peças e produções.' },
  { name: 'Empresário', emoji: '💼', pay: [80, 120], description: 'Gerencie negócios e maximize seus ganhos.' },
  { name: 'Investidor', emoji: '📈', pay: [90, 150], description: 'Gerencie projetos financeiros do sistema.' },
  { name: 'Advogado', emoji: '⚖️', pay: [85, 140], description: 'Analise casos e defenda seus clientes.' },
  { name: 'Chef', emoji: '👨‍🍳', pay: [75, 120], description: 'Comande uma cozinha e crie pratos especiais.' },
  { name: 'Barbeiro', emoji: '💈', pay: [50, 90], description: 'Atenda clientes e cuide do visual deles.' },
  { name: 'Fotógrafo de Eventos', emoji: '📷', pay: [70, 115], description: 'Registre festas, eventos e momentos especiais.' },
  { name: 'Repórter', emoji: '🎙️', pay: [65, 110], description: 'Entreviste pessoas e cubra acontecimentos.' },
  { name: 'Pesquisador', emoji: '🔬', pay: [80, 135], description: 'Investigue assuntos e encontre respostas.' },
  { name: 'Professor de Tecnologia', emoji: '🖥️', pay: [75, 125], description: 'Ensine programação e tecnologia.' },
  { name: 'Técnico de Informática', emoji: '🛠️', pay: [60, 105], description: 'Resolva problemas de computadores e sistemas.' },
  { name: 'Segurança', emoji: '🛡️', pay: [55, 95], description: 'Proteja locais e pessoas.' },
  { name: 'Bibliotecário', emoji: '📚', pay: [45, 80], description: 'Organize livros e ajude visitantes.' },
  { name: 'Escritor', emoji: '✍️', pay: [55, 100], description: 'Escreva histórias, textos e projetos.' },
  { name: 'Ilustrador', emoji: '🖌️', pay: [60, 105], description: 'Crie ilustrações e artes digitais.' },
  { name: 'Animador', emoji: '🎞️', pay: [70, 120], description: 'Produza animações e cenas criativas.' },
  { name: 'Arqueólogo', emoji: '🏺', pay: [75, 125], description: 'Explore locais antigos e encontre relíquias.' },
  { name: 'Explorador', emoji: '🧭', pay: [70, 120], description: 'Participe de expedições e descubra novos lugares.' },
  { name: 'Caçador de Tesouros', emoji: '🗝️', pay: [80, 140], description: 'Procure tesouros em missões especiais.' },
  { name: 'Inventor', emoji: '💡', pay: [85, 145], description: 'Crie invenções e soluções inovadoras.' },
  { name: 'Roboticista', emoji: '🤖', pay: [90, 150], description: 'Construa e programe robôs.' },
  { name: 'Especialista em IA', emoji: '🧠', pay: [100, 165], description: 'Desenvolva soluções usando inteligência artificial.' },
  { name: 'Diretor de Cinema', emoji: '🎬', pay: [95, 155], description: 'Coordene produções cinematográficas.' },
  { name: 'Produtor Musical', emoji: '🎧', pay: [80, 135], description: 'Produza músicas e projetos sonoros.' },
  { name: 'Estilista', emoji: '👗', pay: [65, 110], description: 'Crie estilos e visuais para personagens.' },
  { name: 'Chef de Confeitaria', emoji: '🧁', pay: [60, 105], description: 'Prepare doces e sobremesas especiais.' },
  { name: 'Veterano Espacial', emoji: '🌌', pay: [120, 200], description: 'Participe de missões espaciais avançadas.' },
  { name: 'Agente Secreto', emoji: '🕶️', pay: [110, 185], description: 'Complete missões secretas de alto nível.' },
  { name: 'Caçador de Recompensas', emoji: '🎯', pay: [100, 175], description: 'Complete missões especiais e receba Tokens.' },
  { name: 'Mestre de Guilda', emoji: '🏰', pay: [115, 190], description: 'Comande equipes e organize grandes missões.' },
  { name: 'Líder de Expedição', emoji: '🧗', pay: [100, 170], description: 'Lidere expedições e desafios avançados.' }
];

export { jobs };

export default {
  name: 'vagas',
  aliases: ['empregos', 'trabalhos'],
  category: 'economia',
  description: 'Mostra empregos disponíveis e seus pagamentos',
  async execute({ reply }) {
    const lines = jobs.map((job, i) => `${i + 1}. ${job.emoji} *${job.name}*\n   💰 ${job.pay[0]}–${job.pay[1]} Tokens por trabalho\n   └ ${job.description}`);
    return reply(`╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮\n┃  💼 𝚅𝙰𝙶𝙰𝚂 • 𝚃𝙾𝙶𝙸\n╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯\n\nEscolha sua profissão usando o número:\n\n${lines.join('\n\n')}\n\n💡 Use *.escolher <número>* para entrar em uma profissão.\n💼 Depois use *.trabalhar* para trabalhar.\n📤 Para sair: *.demissao*\n📌 Limite: *3 trabalhos por dia*`);
  }
};
